language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
branches:
  only:
    - main
script:
  - CI=false npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
